// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vesseloracle/vesseloracle/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_51a2d3a975feaee1, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51a2d3a975feaee1, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgCreateVessel struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Imo      string `protobuf:"bytes,2,opt,name=imo,proto3" json:"imo,omitempty"`
	Ts       uint64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Source   string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Lat      int32  `protobuf:"varint,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon      int32  `protobuf:"varint,6,opt,name=lon,proto3" json:"lon,omitempty"`
	Speed    int32  `protobuf:"varint,7,opt,name=speed,proto3" json:"speed,omitempty"`
	Course   int32  `protobuf:"varint,8,opt,name=course,proto3" json:"course,omitempty"`
	Heading  int32  `protobuf:"varint,9,opt,name=heading,proto3" json:"heading,omitempty"`
	Adt      uint64 `protobuf:"varint,10,opt,name=adt,proto3" json:"adt,omitempty"`
	Eta      uint64 `protobuf:"varint,11,opt,name=eta,proto3" json:"eta,omitempty"`
	Name     string `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	Destport string `protobuf:"bytes,13,opt,name=destport,proto3" json:"destport,omitempty"`
	Depport  string `protobuf:"bytes,14,opt,name=depport,proto3" json:"depport,omitempty"`
	Mmsi     string `protobuf:"bytes,15,opt,name=mmsi,proto3" json:"mmsi,omitempty"`
}

func (m *MsgCreateVessel) Reset()         { *m = MsgCreateVessel{} }
func (m *MsgCreateVessel) String() string { return proto.CompactTextString(m) }
func (*MsgCreateVessel) ProtoMessage()    {}
func (*MsgCreateVessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_51a2d3a975feaee1, []int{2}
}
func (m *MsgCreateVessel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateVessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateVessel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateVessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateVessel.Merge(m, src)
}
func (m *MsgCreateVessel) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateVessel) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateVessel.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateVessel proto.InternalMessageInfo

func (m *MsgCreateVessel) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateVessel) GetImo() string {
	if m != nil {
		return m.Imo
	}
	return ""
}

func (m *MsgCreateVessel) GetTs() uint64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *MsgCreateVessel) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MsgCreateVessel) GetLat() int32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *MsgCreateVessel) GetLon() int32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *MsgCreateVessel) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *MsgCreateVessel) GetCourse() int32 {
	if m != nil {
		return m.Course
	}
	return 0
}

func (m *MsgCreateVessel) GetHeading() int32 {
	if m != nil {
		return m.Heading
	}
	return 0
}

func (m *MsgCreateVessel) GetAdt() uint64 {
	if m != nil {
		return m.Adt
	}
	return 0
}

func (m *MsgCreateVessel) GetEta() uint64 {
	if m != nil {
		return m.Eta
	}
	return 0
}

func (m *MsgCreateVessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgCreateVessel) GetDestport() string {
	if m != nil {
		return m.Destport
	}
	return ""
}

func (m *MsgCreateVessel) GetDepport() string {
	if m != nil {
		return m.Depport
	}
	return ""
}

func (m *MsgCreateVessel) GetMmsi() string {
	if m != nil {
		return m.Mmsi
	}
	return ""
}

type MsgCreateVesselResponse struct {
}

func (m *MsgCreateVesselResponse) Reset()         { *m = MsgCreateVesselResponse{} }
func (m *MsgCreateVesselResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateVesselResponse) ProtoMessage()    {}
func (*MsgCreateVesselResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51a2d3a975feaee1, []int{3}
}
func (m *MsgCreateVesselResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateVesselResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateVesselResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateVesselResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateVesselResponse.Merge(m, src)
}
func (m *MsgCreateVesselResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateVesselResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateVesselResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateVesselResponse proto.InternalMessageInfo

type MsgUpdateVessel struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Imo      string `protobuf:"bytes,2,opt,name=imo,proto3" json:"imo,omitempty"`
	Ts       uint64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Source   string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Lat      int32  `protobuf:"varint,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon      int32  `protobuf:"varint,6,opt,name=lon,proto3" json:"lon,omitempty"`
	Speed    int32  `protobuf:"varint,7,opt,name=speed,proto3" json:"speed,omitempty"`
	Course   int32  `protobuf:"varint,8,opt,name=course,proto3" json:"course,omitempty"`
	Heading  int32  `protobuf:"varint,9,opt,name=heading,proto3" json:"heading,omitempty"`
	Adt      uint64 `protobuf:"varint,10,opt,name=adt,proto3" json:"adt,omitempty"`
	Eta      uint64 `protobuf:"varint,11,opt,name=eta,proto3" json:"eta,omitempty"`
	Name     string `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	Destport string `protobuf:"bytes,13,opt,name=destport,proto3" json:"destport,omitempty"`
	Depport  string `protobuf:"bytes,14,opt,name=depport,proto3" json:"depport,omitempty"`
	Mmsi     string `protobuf:"bytes,15,opt,name=mmsi,proto3" json:"mmsi,omitempty"`
}

func (m *MsgUpdateVessel) Reset()         { *m = MsgUpdateVessel{} }
func (m *MsgUpdateVessel) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateVessel) ProtoMessage()    {}
func (*MsgUpdateVessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_51a2d3a975feaee1, []int{4}
}
func (m *MsgUpdateVessel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateVessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateVessel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateVessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateVessel.Merge(m, src)
}
func (m *MsgUpdateVessel) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateVessel) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateVessel.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateVessel proto.InternalMessageInfo

func (m *MsgUpdateVessel) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateVessel) GetImo() string {
	if m != nil {
		return m.Imo
	}
	return ""
}

func (m *MsgUpdateVessel) GetTs() uint64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *MsgUpdateVessel) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MsgUpdateVessel) GetLat() int32 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *MsgUpdateVessel) GetLon() int32 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *MsgUpdateVessel) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *MsgUpdateVessel) GetCourse() int32 {
	if m != nil {
		return m.Course
	}
	return 0
}

func (m *MsgUpdateVessel) GetHeading() int32 {
	if m != nil {
		return m.Heading
	}
	return 0
}

func (m *MsgUpdateVessel) GetAdt() uint64 {
	if m != nil {
		return m.Adt
	}
	return 0
}

func (m *MsgUpdateVessel) GetEta() uint64 {
	if m != nil {
		return m.Eta
	}
	return 0
}

func (m *MsgUpdateVessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgUpdateVessel) GetDestport() string {
	if m != nil {
		return m.Destport
	}
	return ""
}

func (m *MsgUpdateVessel) GetDepport() string {
	if m != nil {
		return m.Depport
	}
	return ""
}

func (m *MsgUpdateVessel) GetMmsi() string {
	if m != nil {
		return m.Mmsi
	}
	return ""
}

type MsgUpdateVesselResponse struct {
}

func (m *MsgUpdateVesselResponse) Reset()         { *m = MsgUpdateVesselResponse{} }
func (m *MsgUpdateVesselResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateVesselResponse) ProtoMessage()    {}
func (*MsgUpdateVesselResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51a2d3a975feaee1, []int{5}
}
func (m *MsgUpdateVesselResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateVesselResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateVesselResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateVesselResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateVesselResponse.Merge(m, src)
}
func (m *MsgUpdateVesselResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateVesselResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateVesselResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateVesselResponse proto.InternalMessageInfo

type MsgDeleteVessel struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Imo     string `protobuf:"bytes,2,opt,name=imo,proto3" json:"imo,omitempty"`
	Ts      uint64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Source  string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
}

func (m *MsgDeleteVessel) Reset()         { *m = MsgDeleteVessel{} }
func (m *MsgDeleteVessel) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteVessel) ProtoMessage()    {}
func (*MsgDeleteVessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_51a2d3a975feaee1, []int{6}
}
func (m *MsgDeleteVessel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteVessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteVessel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteVessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteVessel.Merge(m, src)
}
func (m *MsgDeleteVessel) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteVessel) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteVessel.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteVessel proto.InternalMessageInfo

func (m *MsgDeleteVessel) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteVessel) GetImo() string {
	if m != nil {
		return m.Imo
	}
	return ""
}

func (m *MsgDeleteVessel) GetTs() uint64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *MsgDeleteVessel) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type MsgDeleteVesselResponse struct {
}

func (m *MsgDeleteVesselResponse) Reset()         { *m = MsgDeleteVesselResponse{} }
func (m *MsgDeleteVesselResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteVesselResponse) ProtoMessage()    {}
func (*MsgDeleteVesselResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51a2d3a975feaee1, []int{7}
}
func (m *MsgDeleteVesselResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteVesselResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteVesselResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteVesselResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteVesselResponse.Merge(m, src)
}
func (m *MsgDeleteVesselResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteVesselResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteVesselResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteVesselResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "vesseloracle.vesseloracle.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "vesseloracle.vesseloracle.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreateVessel)(nil), "vesseloracle.vesseloracle.MsgCreateVessel")
	proto.RegisterType((*MsgCreateVesselResponse)(nil), "vesseloracle.vesseloracle.MsgCreateVesselResponse")
	proto.RegisterType((*MsgUpdateVessel)(nil), "vesseloracle.vesseloracle.MsgUpdateVessel")
	proto.RegisterType((*MsgUpdateVesselResponse)(nil), "vesseloracle.vesseloracle.MsgUpdateVesselResponse")
	proto.RegisterType((*MsgDeleteVessel)(nil), "vesseloracle.vesseloracle.MsgDeleteVessel")
	proto.RegisterType((*MsgDeleteVesselResponse)(nil), "vesseloracle.vesseloracle.MsgDeleteVesselResponse")
}

func init() {
	proto.RegisterFile("vesseloracle/vesseloracle/tx.proto", fileDescriptor_51a2d3a975feaee1)
}

var fileDescriptor_51a2d3a975feaee1 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0x41, 0x6f, 0x12, 0x41,
	0x14, 0x66, 0xa1, 0xd0, 0x32, 0xc5, 0x56, 0x27, 0xc4, 0x0e, 0x1c, 0x56, 0xca, 0xc1, 0x10, 0x8c,
	0x10, 0x31, 0xf1, 0x50, 0x13, 0x13, 0xb1, 0xd7, 0x26, 0x66, 0x8d, 0x1e, 0xbc, 0x98, 0x91, 0x7d,
	0xd9, 0x6e, 0xc2, 0xee, 0x6c, 0x66, 0x86, 0xa6, 0xbd, 0x19, 0x8f, 0x9e, 0xfc, 0x19, 0x1e, 0x39,
	0xf8, 0x23, 0x7a, 0x30, 0xb1, 0xf1, 0xe4, 0xc9, 0x28, 0x1c, 0xf8, 0x1b, 0x66, 0x66, 0x96, 0xb2,
	0x8b, 0xb4, 0xcb, 0xa5, 0x37, 0x2f, 0xf0, 0xbe, 0x6f, 0xde, 0xbe, 0xef, 0xbd, 0x6f, 0xe0, 0x2d,
	0x6a, 0x9e, 0x80, 0x10, 0x30, 0x64, 0x9c, 0x0e, 0x86, 0xd0, 0x4d, 0x01, 0x79, 0xda, 0x89, 0x38,
	0x93, 0x0c, 0xd7, 0x92, 0x74, 0x27, 0x09, 0xea, 0x77, 0x68, 0xe0, 0x87, 0xac, 0xab, 0x3f, 0x4d,
	0x76, 0x7d, 0x6f, 0xc0, 0x44, 0xc0, 0x44, 0x37, 0x10, 0x5e, 0xf7, 0xe4, 0x91, 0xfa, 0x8a, 0x0f,
	0x6a, 0xe6, 0xe0, 0x9d, 0x46, 0x5d, 0x03, 0xe2, 0xa3, 0xaa, 0xc7, 0x3c, 0x66, 0x78, 0x15, 0xc5,
	0xec, 0xfd, 0xab, 0x7b, 0x8b, 0x28, 0xa7, 0x81, 0xc8, 0xce, 0x33, 0xc0, 0xe4, 0x35, 0xbf, 0x5b,
	0x68, 0xf7, 0x48, 0x78, 0xaf, 0x23, 0x97, 0x4a, 0x78, 0xa9, 0x2b, 0xe0, 0x27, 0xa8, 0x4c, 0x47,
	0xf2, 0x98, 0x71, 0x5f, 0x9e, 0x11, 0xab, 0x61, 0xb5, 0xca, 0x7d, 0xf2, 0xe3, 0xeb, 0xc3, 0x6a,
	0xdc, 0xde, 0x73, 0xd7, 0xe5, 0x20, 0xc4, 0x2b, 0xc9, 0xfd, 0xd0, 0x73, 0x16, 0xa9, 0xf8, 0x10,
	0x95, 0x4c, 0x0f, 0x24, 0xdf, 0xb0, 0x5a, 0xdb, 0xbd, 0xfd, 0xce, 0x95, 0x26, 0x75, 0x8c, 0x54,
	0xbf, 0x7c, 0xfe, 0xeb, 0x5e, 0xee, 0xcb, 0x6c, 0xdc, 0xb6, 0x9c, 0xf8, 0xd9, 0x83, 0x67, 0x1f,
	0x67, 0xe3, 0xf6, 0xa2, 0xea, 0xa7, 0xd9, 0xb8, 0xfd, 0x20, 0xd5, 0xff, 0x69, 0x7a, 0x9c, 0xa5,
	0xee, 0x9b, 0x35, 0xb4, 0xb7, 0x44, 0x39, 0x20, 0x22, 0x16, 0x0a, 0x68, 0xfe, 0xc9, 0xeb, 0x61,
	0x5f, 0x70, 0xa0, 0x12, 0xde, 0xe8, 0x22, 0x98, 0xa0, 0xcd, 0x81, 0xc2, 0x8c, 0x9b, 0x51, 0x9d,
	0x39, 0xc4, 0xb7, 0x51, 0xc1, 0x0f, 0x98, 0x9e, 0xa5, 0xec, 0xa8, 0x10, 0xef, 0xa0, 0xbc, 0x14,
	0xa4, 0xd0, 0xb0, 0x5a, 0x1b, 0x4e, 0x5e, 0x0a, 0x7c, 0x17, 0x95, 0x04, 0x1b, 0xf1, 0x01, 0x90,
	0x0d, 0x9d, 0x14, 0x23, 0xf5, 0xe4, 0x90, 0x4a, 0x52, 0x6c, 0x58, 0xad, 0xa2, 0xa3, 0x42, 0xcd,
	0xb0, 0x90, 0x94, 0x62, 0x86, 0x85, 0xb8, 0x8a, 0x8a, 0x22, 0x02, 0x70, 0xc9, 0xa6, 0xe6, 0x0c,
	0x50, 0x15, 0x07, 0x6c, 0xc4, 0x05, 0x90, 0x2d, 0x4d, 0xc7, 0x48, 0x75, 0x79, 0x0c, 0xd4, 0xf5,
	0x43, 0x8f, 0x94, 0xf5, 0xc1, 0x1c, 0xaa, 0xca, 0xd4, 0x95, 0x04, 0xe9, 0xa6, 0x54, 0xa8, 0x18,
	0x90, 0x94, 0x6c, 0x1b, 0x06, 0x24, 0xc5, 0x18, 0x6d, 0x84, 0x34, 0x00, 0x52, 0xd1, 0x5d, 0xea,
	0x18, 0xd7, 0xd1, 0x96, 0x0b, 0x42, 0x46, 0x8c, 0x4b, 0x72, 0x4b, 0xf3, 0x97, 0x58, 0xa9, 0xb9,
	0x10, 0xe9, 0xa3, 0x1d, 0xe3, 0x49, 0x0c, 0x55, 0xa5, 0x20, 0x10, 0x3e, 0xd9, 0x35, 0x95, 0x54,
	0x7c, 0x50, 0x51, 0x17, 0x36, 0x77, 0x2d, 0xb6, 0x3f, 0x69, 0xf1, 0xb2, 0xfd, 0xe6, 0x6a, 0xfe,
	0xdb, 0x7f, 0x83, 0xf6, 0x27, 0x2d, 0xbe, 0xb4, 0x5f, 0x68, 0xf7, 0x0f, 0x61, 0x08, 0x37, 0xe9,
	0xfe, 0xca, 0x7e, 0x92, 0xa2, 0xf3, 0x7e, 0x7a, 0xdf, 0x0a, 0xa8, 0x70, 0x24, 0x3c, 0x1c, 0xa2,
	0x4a, 0x6a, 0xfd, 0xb4, 0xaf, 0x59, 0x1b, 0x4b, 0xff, 0xec, 0x7a, 0x6f, 0xfd, 0xdc, 0xb9, 0xae,
	0xd2, 0x4b, 0x6d, 0x80, 0x0c, 0xbd, 0x64, 0x6e, 0x96, 0xde, 0xaa, 0x9f, 0xfd, 0x62, 0xbe, 0xf5,
	0xf4, 0x92, 0xb9, 0xeb, 0xcd, 0xf7, 0xaf, 0x5e, 0xea, 0x92, 0x33, 0xf4, 0x92, 0xb9, 0x59, 0x7a,
	0xab, 0xee, 0xb1, 0x5e, 0xfc, 0xa0, 0xf6, 0x77, 0xff, 0xe9, 0xf9, 0xc4, 0xb6, 0x2e, 0x26, 0xb6,
	0xf5, 0x7b, 0x62, 0x5b, 0x9f, 0xa7, 0x76, 0xee, 0x62, 0x6a, 0xe7, 0x7e, 0x4e, 0xed, 0xdc, 0xdb,
	0xfd, 0xeb, 0xd6, 0xb7, 0x3c, 0x8b, 0x40, 0xbc, 0x2f, 0xe9, 0xb7, 0xd1, 0xe3, 0xbf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x32, 0x18, 0xd5, 0xc8, 0x7b, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	CreateVessel(ctx context.Context, in *MsgCreateVessel, opts ...grpc.CallOption) (*MsgCreateVesselResponse, error)
	UpdateVessel(ctx context.Context, in *MsgUpdateVessel, opts ...grpc.CallOption) (*MsgUpdateVesselResponse, error)
	DeleteVessel(ctx context.Context, in *MsgDeleteVessel, opts ...grpc.CallOption) (*MsgDeleteVesselResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/vesseloracle.vesseloracle.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateVessel(ctx context.Context, in *MsgCreateVessel, opts ...grpc.CallOption) (*MsgCreateVesselResponse, error) {
	out := new(MsgCreateVesselResponse)
	err := c.cc.Invoke(ctx, "/vesseloracle.vesseloracle.Msg/CreateVessel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateVessel(ctx context.Context, in *MsgUpdateVessel, opts ...grpc.CallOption) (*MsgUpdateVesselResponse, error) {
	out := new(MsgUpdateVesselResponse)
	err := c.cc.Invoke(ctx, "/vesseloracle.vesseloracle.Msg/UpdateVessel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteVessel(ctx context.Context, in *MsgDeleteVessel, opts ...grpc.CallOption) (*MsgDeleteVesselResponse, error) {
	out := new(MsgDeleteVesselResponse)
	err := c.cc.Invoke(ctx, "/vesseloracle.vesseloracle.Msg/DeleteVessel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	CreateVessel(context.Context, *MsgCreateVessel) (*MsgCreateVesselResponse, error)
	UpdateVessel(context.Context, *MsgUpdateVessel) (*MsgUpdateVesselResponse, error)
	DeleteVessel(context.Context, *MsgDeleteVessel) (*MsgDeleteVesselResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) CreateVessel(ctx context.Context, req *MsgCreateVessel) (*MsgCreateVesselResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVessel not implemented")
}
func (*UnimplementedMsgServer) UpdateVessel(ctx context.Context, req *MsgUpdateVessel) (*MsgUpdateVesselResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVessel not implemented")
}
func (*UnimplementedMsgServer) DeleteVessel(ctx context.Context, req *MsgDeleteVessel) (*MsgDeleteVesselResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVessel not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vesseloracle.vesseloracle.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateVessel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateVessel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateVessel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vesseloracle.vesseloracle.Msg/CreateVessel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateVessel(ctx, req.(*MsgCreateVessel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateVessel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateVessel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateVessel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vesseloracle.vesseloracle.Msg/UpdateVessel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateVessel(ctx, req.(*MsgUpdateVessel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteVessel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteVessel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteVessel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vesseloracle.vesseloracle.Msg/DeleteVessel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteVessel(ctx, req.(*MsgDeleteVessel))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vesseloracle.vesseloracle.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateVessel",
			Handler:    _Msg_CreateVessel_Handler,
		},
		{
			MethodName: "UpdateVessel",
			Handler:    _Msg_UpdateVessel_Handler,
		},
		{
			MethodName: "DeleteVessel",
			Handler:    _Msg_DeleteVessel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vesseloracle/vesseloracle/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateVessel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateVessel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateVessel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Mmsi) > 0 {
		i -= len(m.Mmsi)
		copy(dAtA[i:], m.Mmsi)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Mmsi)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.Depport) > 0 {
		i -= len(m.Depport)
		copy(dAtA[i:], m.Depport)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Depport)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.Destport) > 0 {
		i -= len(m.Destport)
		copy(dAtA[i:], m.Destport)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Destport)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x62
	}
	if m.Eta != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Eta))
		i--
		dAtA[i] = 0x58
	}
	if m.Adt != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Adt))
		i--
		dAtA[i] = 0x50
	}
	if m.Heading != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Heading))
		i--
		dAtA[i] = 0x48
	}
	if m.Course != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Course))
		i--
		dAtA[i] = 0x40
	}
	if m.Speed != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Speed))
		i--
		dAtA[i] = 0x38
	}
	if m.Lon != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Lon))
		i--
		dAtA[i] = 0x30
	}
	if m.Lat != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Lat))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x22
	}
	if m.Ts != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Ts))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Imo) > 0 {
		i -= len(m.Imo)
		copy(dAtA[i:], m.Imo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Imo)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateVesselResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateVesselResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateVesselResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateVessel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateVessel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateVessel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Mmsi) > 0 {
		i -= len(m.Mmsi)
		copy(dAtA[i:], m.Mmsi)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Mmsi)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.Depport) > 0 {
		i -= len(m.Depport)
		copy(dAtA[i:], m.Depport)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Depport)))
		i--
		dAtA[i] = 0x72
	}
	if len(m.Destport) > 0 {
		i -= len(m.Destport)
		copy(dAtA[i:], m.Destport)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Destport)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x62
	}
	if m.Eta != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Eta))
		i--
		dAtA[i] = 0x58
	}
	if m.Adt != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Adt))
		i--
		dAtA[i] = 0x50
	}
	if m.Heading != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Heading))
		i--
		dAtA[i] = 0x48
	}
	if m.Course != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Course))
		i--
		dAtA[i] = 0x40
	}
	if m.Speed != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Speed))
		i--
		dAtA[i] = 0x38
	}
	if m.Lon != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Lon))
		i--
		dAtA[i] = 0x30
	}
	if m.Lat != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Lat))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x22
	}
	if m.Ts != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Ts))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Imo) > 0 {
		i -= len(m.Imo)
		copy(dAtA[i:], m.Imo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Imo)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateVesselResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateVesselResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateVesselResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteVessel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteVessel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteVessel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x22
	}
	if m.Ts != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Ts))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Imo) > 0 {
		i -= len(m.Imo)
		copy(dAtA[i:], m.Imo)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Imo)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteVesselResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteVesselResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteVesselResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateVessel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Imo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Ts != 0 {
		n += 1 + sovTx(uint64(m.Ts))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Lat != 0 {
		n += 1 + sovTx(uint64(m.Lat))
	}
	if m.Lon != 0 {
		n += 1 + sovTx(uint64(m.Lon))
	}
	if m.Speed != 0 {
		n += 1 + sovTx(uint64(m.Speed))
	}
	if m.Course != 0 {
		n += 1 + sovTx(uint64(m.Course))
	}
	if m.Heading != 0 {
		n += 1 + sovTx(uint64(m.Heading))
	}
	if m.Adt != 0 {
		n += 1 + sovTx(uint64(m.Adt))
	}
	if m.Eta != 0 {
		n += 1 + sovTx(uint64(m.Eta))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Destport)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Depport)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Mmsi)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateVesselResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateVessel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Imo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Ts != 0 {
		n += 1 + sovTx(uint64(m.Ts))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Lat != 0 {
		n += 1 + sovTx(uint64(m.Lat))
	}
	if m.Lon != 0 {
		n += 1 + sovTx(uint64(m.Lon))
	}
	if m.Speed != 0 {
		n += 1 + sovTx(uint64(m.Speed))
	}
	if m.Course != 0 {
		n += 1 + sovTx(uint64(m.Course))
	}
	if m.Heading != 0 {
		n += 1 + sovTx(uint64(m.Heading))
	}
	if m.Adt != 0 {
		n += 1 + sovTx(uint64(m.Adt))
	}
	if m.Eta != 0 {
		n += 1 + sovTx(uint64(m.Eta))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Destport)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Depport)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Mmsi)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateVesselResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteVessel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Imo)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Ts != 0 {
		n += 1 + sovTx(uint64(m.Ts))
	}
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteVesselResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateVessel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateVessel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateVessel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Imo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Imo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ts", wireType)
			}
			m.Ts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ts |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lat", wireType)
			}
			m.Lat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lat |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lon", wireType)
			}
			m.Lon = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lon |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Speed", wireType)
			}
			m.Speed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Speed |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Course", wireType)
			}
			m.Course = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Course |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Heading", wireType)
			}
			m.Heading = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Heading |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Adt", wireType)
			}
			m.Adt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Adt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eta", wireType)
			}
			m.Eta = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Eta |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destport", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destport = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depport", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depport = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mmsi", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mmsi = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateVesselResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateVesselResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateVesselResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateVessel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateVessel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateVessel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Imo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Imo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ts", wireType)
			}
			m.Ts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ts |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lat", wireType)
			}
			m.Lat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lat |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lon", wireType)
			}
			m.Lon = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Lon |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Speed", wireType)
			}
			m.Speed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Speed |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Course", wireType)
			}
			m.Course = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Course |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Heading", wireType)
			}
			m.Heading = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Heading |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Adt", wireType)
			}
			m.Adt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Adt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Eta", wireType)
			}
			m.Eta = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Eta |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destport", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destport = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depport", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depport = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mmsi", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mmsi = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateVesselResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateVesselResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateVesselResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteVessel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteVessel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteVessel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Imo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Imo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ts", wireType)
			}
			m.Ts = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Ts |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteVesselResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteVesselResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteVesselResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
