services:
  vesseloracle-node-prod:
    container_name: vesseloracle-node-prod
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    ports:
      - "26657:26657"
      - "26656:26656"
      - "9090:9090"
      - "4500:4500"
      - "1317:1317"
    restart: always
