global:
    api-listen-addr: :5183
    timeout: 10s
    memo: ""
    light-cache-size: 20
chains:
    cardano:
        type: cardano
        value:
            key-directory: /home/datlt/Documents/sosc-relayer/test/ibctest/keys/cardano
            key: key-cardano-test
            chain-id: cardano
            rpc-addr: http://localhost:5001
            account-prefix: ""
            keyring-backend: test
            gas-adjustment: 0
            gas-prices: ""
            min-gas-amount: 0
            max-gas-amount: 0
            debug: false
            timeout: 60s
            block-timeout: ""
            output-format: ""
            sign-mode: ""
            extra-codecs: []
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
    cosmos:
        type: cosmos
        value:
            key-directory: /home/datlt/Documents/sosc-relayer/test/ibctest/keys/sidechain
            key: key-cosmos
            chain-id: sidechain
            rpc-addr: http://localhost:26657
            account-prefix: cosmos
            keyring-backend: test
            gas-adjustment: 1.1
            gas-prices: ""
            min-gas-amount: 0
            max-gas-amount: 0
            debug: false
            timeout: 60s
            block-timeout: ""
            output-format: ""
            sign-mode: ""
            extra-codecs: []
            coin-type: null
            signing-algorithm: ""
            broadcast-mode: batch
            min-loop-duration: 0s
            extension-options: []
            feegrants: null
paths:
    demo:
        src:
            chain-id: cardano
            client-id: ibc_client-53
            connection-id: connection-45
        dst:
            chain-id: sidechain
            client-id: 099-cardano-62
            connection-id: connection-44
        src-channel-filter:
            rule: ""
            channel-list: []
