version: 1
validation: sovereign
accounts: 
  - name: alice
    coins:
    - 20000token
    - 200000000stake
  - name: bob
    coins:
    - 10000token
    - 100000000stake
  - name: relayer
    coins:
      - 10000token
      - 100000000stake
    mnemonic: engage vote never tired enter brain chat loan coil venture soldier shine awkward keen delay link mass print venue federal ankle valid upgrade balance
  - name: ds0
    coins:
    - 10000token
    - 100000000stake
  - name: ds1
    coins:
    - 10000token
    - 100000000stake
  - name: ds2
    coins:
    - 10000token
    - 100000000stake
  - name: ds3
    coins:
    - 10000token
    - 100000000stake
  - name: ds4
    coins:
    - 10000token
    - 100000000stake
  - name: ds5
    coins:
    - 10000token
    - 100000000stake
  - name: ds6
    coins:
    - 10000token
    - 100000000stake
  - name: ds7
    coins:
    - 10000token
    - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
  port: 4500
validators:
- name: alice
  bonded: 100000000stake
genesis:
  chain_id: vesseloracle
  app_state:
    ibc:
      client_genesis:
        clients: []
        clients_consensus: []
        clients_metadata: []
        params:
          allowed_clients:
            - "099-cardano"
            - "07-tendermint"
            - "06-solomachine"
        create_localhost: false
        next_client_sequence: 0
      connection_genesis:
        connections: []
        client_connection_paths: []
        next_connection_sequence: 0
        params:
          max_expected_time_per_block: 30000000000
      channel_genesis:
        channels: []
        acknowledgements: []
        commitments: []
        receipts: []
        send_sequences: []
        recv_sequences: []
        ack_sequences: []
        next_channel_sequence: 0

    transfer:
      port_id: "transfer"
      denom_traces: []
      params:
        send_enabled: true
        receive_enabled: true

    feeibc:
      identified_fees: []
      fee_enabled_channels: []
      registered_payees: []
      registered_counterparty_payees: []
      forward_relayers: []

    packetfowardmiddleware:
      params:
        fee_percentage: "0.100000000000000000"
build:
  binary: "vesseloracle"